[setport]
#btdongleport = com7
#btdonglerate = 115200
#blue_dongle_read_write_uuid_port = com18
#blue_dongle_read_write_uuid_rate = 115200
#DM3058 = USB0::0x1AB1::0x09C4::DM3R241300641::INSTR
#DM3058_baudrate = 9600
#DM3058_S2 = USB0::0x1AB1::0x09C4::DM3R241300641::INSTR
#DM3058_baudrate_S2 = 9600
#mic_fft_dect = 1
#Relay_board = COM2
#Relay_board_baudrate = 9600
#Relay_board2 = COM15
#Relay_board2_baudrate = 9600
#Relay_board3 = COM1
#Relay_board3_baudrate = 9600
#sk_Relay_board = COM18
#sk_Relay_board_baudrate = 9600
#sk_Relay_board2 = COM15
#sk_Relay_board2_baudrate = 9600
#sk_Relay_board3 = COM1
#sk_Relay_board3_baudrate = 9600
#ST_Relay_board1 = COM1
#ST_Relay_board1_baudrate = 9600
#innove_Relay_board = COM9
#innove_Relay_board2 = COM9
#DAM_3158A_DAQ_port = COM44
#DAM_3158A_DAQ_baudrate = 9600
#myrelay_board = COM1
#myrelay_board_baudrate = 115200
#myrelay_board2 = COM1
#myrelay_board2_baudrate = 115200
#TDM9001_2A = COM45
#TDM9001_2A_baudrate = 115200
#TMD1501_50 = COM1
#TMD1501_50_baudrate = 19200
#chroma19701 = com1
#chroma19701_baudrate = 19200
#TRM1201 = COM4
#TRM1201_baudrate = 19200
#MPIO_comline = COM2
#MPIO_comline_baudrate = 9600
#MP_COMLINE1 = COM21
#MP_COMLINE1_baudrate = 9600
#MP_COMLINE2 = COM2
#MP_COMLINE2_baudrate = 9600
#mpio_weite_serial_can_port = com18
#mpio_weite_serial_can_baudrate = 9600
#comline2 = COM34
#comline2_baudrate = 460800
#comline = COM8
#comline_baudrate = 460800
#industrial_scanner_port = COM2
#industrial_scanner_baudrate = 9600
#comline_x100_host = COM13
#comline_x100_host_baudrate = 115200
#comline_x100_sub = COM1
#comline_x100_sub_baudrate = 115200
#led_sensor = COM45
#led_sensor_baudrate = 115200
#color_assyer = COM9
#color_assyer_baudrate = 57600
#color_assyer2 = COM11
#color_assyer_baudrate2 = 57600
#color_assyer3 = COM11
#color_assyer_baudrate3 = 57600
#color_assyer4 = COM11
#color_assyer_baudrate4 = 57600
#vc8145cmeter = com18
#vc8145cmeter_baudrate = 9600
#gpd3033 = com28
#gpd3033_baudrate = 9600
#HMS3000port = COM6
#HMS3000_baudrate = 115200
#smartFreqSpecport = com1
#smartFreqSpecbaudrate = 115200
#comlineforingo_led_port = com6
#comlineforingo_led_baudrate = 57600
#shieldboxport = com1
#shieldboxbaudrate = 9600
#comlineformicread_port = com4
#comlineformicread_baudrate = 9600
#cmw100address = ttttttt
#cmw100address_for_lte = abcded
#SRND_CM_12DI_port = COM9
#SRND_CM_12DI_baudrate = 9600
#SRND_CM_40DI_port = COM6
#SRND_CM_40DI_baudrate = 9600
#SRND_COM_VE30_port = COM1
#SRND_COM_VE30_baudrate = 9600
#luoyinji_port = COM2
#luoyinji_baudrate = 115200
#DPS3005port = COM12
#DPS3005_baudrate = 9600
#ampdbmsport = COM14
#ampdbms_baudrate = 56000
#IVYTECH3610port = com1
#IVYTECH3610baudrate = 9600
#Festoolport = COM10
#Festoolbaudrate = 115200
Festool_eol_addr = 3
Festool_contol_add = 4
Festversion = 0
FestPart_number = 0
#hp_2016_thrust_meter_port = com12
#hp_2016_thrust_meter_baudrate = 9600
#ans_jp5030_power_port = com1
#ans_jp5030_power_port_baudrate = 9600
#RevAir_com_port = com9
#RevAir_com_baudrate = 9600
#AC_SOURCE_IVYTECH_com_port = COM10
#AC_SOURCE_IVYTECH_port_baudrate = 9600
#e_control_can_usb_port = com7
#e_control_can_usb_port_baudrate = 9600
#RFExplorer_port = com10
#RFExplorer_baudrate = 500000
#baby_happy_serial_port = com20
#baby_happy_serial_port_baudrate = 115200
#schsa_project_blue_commander4button_port = com1
#schsa_project_blue_commander4button_baudrate = 9600
#schsa_project_blue_commander4repeat_port = com1
#schsa_project_blue_commander4repeat_baudrate = 9600
#schsa_project_blue_commander4wpel_port = com1
#schsa_project_blue_commander4wpel_baudrate = 9600
#esp32_rf_gener_port = com1
#esp32_rf_gener_port_baudrate = 115200
#chroma_dc_elecronic_63200_port = com10
#chroma_dc_elecronic_63200_baudrate = 9600
#Tek_TPS2040_Oscilloscopes_port = com10
#Tek_TPS2040_Oscilloscopes_baudrate = 19200
#AC_POWER_SUPPLY_1_port = com10
#AC_POWER_SUPPLY_1_baudrate = 9600
#victor_4090C_port = com8
#victor_4090C_baudrate = 9600
#BIOFI_PROD_port = com35
#BIOFI_PROD_baudrate = 115200
#pycom_1_port = com2
#pycom_1_baudrate = 115200
#UTE9901_Power_meter = com1
#UTE9901_Power_meter_baudrate = 9600
#dielectric_strength_tester_ut5310 = com1
#dielectric_strength_tester_ut5310_baudrate = com1
#plc_xx_com = com15
#plc_com_xx_baudrate = 115200
#rek_rk2512n_port = com15
#rek_rk2512n_baudrate = 9600
#usb2185_port = 1
#legrand_proj_serial_port = com6
#legrand_proj_serial_baudrate = 9600
#pk9015a_16_analog_acquisition_port = com1
#pk9015a_16_analog_acquisition_baudrate = 9600
#vantage_serial_can_port = com5
#vantage_serial_can_baudrate = 9600
#chuangxincan = 1
#weite_serial_can_port = com34
#weite_serial_can_baudrate = 9600
#desaysv_serial_port = com1
#desaysv_serial_baudrate = 9600
#IV3003T_DC_power_port = com1
#IV3003T_DC_power_baudrate = 9600
#Rigol_ds1202 = USB0::0x1AB1::0x04CE::DS1ZC232402648::INSTR
#vantage_new_hb_can_serial_port=com11
#vantage_new_hb_can_serial_baudrate=9600
#vantage_new_ui_serial_port=com11
#vantage_new_ui_serial_baudrate=9600


;Rigol_ds1202 = TCPIP0::169.254.230.176::inst0::INSTR
#cop_serial_port = com6
#cop_serial_baudrate = 9600
#toc_serial_port = com6
#toc_serial_baudrate = 9600
b = 456
c = 789

[hackrf]
hackrf_sweepPath = hackrf_sweep.exe
bt_wifi_parameter = -f2400:2404 -a1 -p1 -l24 -g20 -n8192 -w10000 -N2000
cc1310_parameter = -f423:443 -a1 -p1 -l24 -g20 -n8192 -w10000 -N2000
cc1310_900M_1_parameter = -f890:910 -a1 -p1 -l24 -g20 -n8192 -w10000 -N2000
cc1310_900M_2_parameter = -f910:930 -a1 -p1 -l24 -g20 -n8192 -w10000 -N2000
cc1310_900M_3_parameter = -f920:940 -a1 -p1 -l24 -g20 -n8192 -w10000 -N2000
wifi_5G_parameter = -f5170:5190 -a1 -p1 -l24 -g20 -n8192 -w10000 -N2000
hackrf_bt_pathloss = 0
hackrf_wifi_pathloss = 0
hackrf_wifi_5G_pathloss = 0
hackrf_cc1310_pathloss = -6
hackrf_cc1310_900_1_pathloss = 0
hackrf_cc1310_900_2_pathloss = 0
hackrf_cc1310_900_3_pathloss = 0

[cmw100statuscheck]
statusyear = 2018
statusmonth = 6
statusday = 16
statushour = 23
checkcycle = 4

[cmw100ParameterSet]
sample1sn = 12345
sample2sn = 45678
sample1_wifi_standardvalues = -3
sample2_wifi_standardvalues = -5
sample1_cc1310_standardvalues = -7
sample2_cc1310_standardvalues = -10
sample1_bluetooth_standardvalues = -3
sample2_bluetooth_standardvalues = -5
wifipathloss = 0
buletoothpathloss = 5
cc1310loss = -0.139308
extatt = 0
goldsample1sn = 0000000000
goldsample2sn = 0000000000
goldsample3sn = 0000000000
goldsample1_bt_ch0_standardvalues = 10
goldsample1_bt_ch20_standardvalues = 10
goldsample1_bt_ch39_standardvalues = 10
goldsample2_bt_ch0_standardvalues = 10
goldsample2_bt_ch20_standardvalues = 10
goldsample2_bt_ch39_standardvalues = 10
goldsample3_bt_ch0_standardvalues = 10
goldsample3_bt_ch20_standardvalues = 10
goldsample3_bt_ch39_standardvalues = 10
buletoothpathloss_ch0 = 0
buletoothpathloss_ch20 = 0
buletoothpathloss_ch39 = -4.3

[statu]
NG_RUN = no
case_jumper = 0
#plc_auto = 1
input_status = 1

[language]
english = 1

[recorder]
time0OK = 83
time1OK = 34
time2OK = 26
time3OK = 6
time4OK = 0
time5OK = 0
time6OK = 0
time7OK = 60
time8OK = 429
time9OK = 768
time10OK = 817
time11OK = 819
time12OK = 283
time13OK = 835
time14OK = 701
time15OK = 742
time16OK = 499
time17OK = 15
time18OK = 301
time19OK = 597
time20OK = 707
time21OK = 306
time22OK = 491
time23OK = 402
time0NG = 46
time1NG = 10
time2NG = 1
time3NG = 17
time4NG = 0
time5NG = 0
time6NG = 1
time7NG = 29
time8NG = 771
time9NG = 581
time10NG = 582
time11NG = 328
time12NG = 23
time13NG = 159
time14NG = 234
time15NG = 721
time16NG = 396
time17NG = 4
time18NG = 180
time19NG = 393
time20NG = 742
time21NG = 282
time22NG = 286
time23NG = 178
title = 11185
titleok = 6446
titleng = 4471

[setbarcode]
barlen = 5

;;barreg = ^X100\S\s\d{9}$
;;barreg = ^1P02-96568.{3}SE17.{13}$
barreg = ^S\d{1}$

;true 为有条码记录
barenable = true

[setproduct]
#setalalonlogenable = 1
#avalon_net_work_test = http://192.168.89.127:7755
#mecury_net_work_test = http://192.168.8.104:7755
project = desay_function_test
name = desay_function_test_v01
fixturename = fct-1111-00c
personal_number = 12345
url = http://192.168.89.65:8888/postdata.aardio
surl = http://192.168.11.220:8081/api/v1/trans/test-station
macsavepath = d:\\
ifautotest = true
logger = smx_mes_logger
rflogfilebackup = 1
MACADDR = 00000000005a;FFFFFFFFFFFF
hbi_prefix = 7C51
#hbi_region = 2
#hbi_test_stestion_type = 1
product_info = FW ver =>1.0.0.1
line_number = CELL01
work_station = FCT-001
lock = true

[MES_SET]
sourceID = FCT
deviceID = FCT-for-testing
url = http://192.168.13.225/ims-cust/api/iot/fct/getFctLbid

[_params_]
Document_Name = Desay_MD4862_MAIN_TEST

;Fixture_id=FCT-001-00C
[wiring_harness]
cable_test_production_line = 1
cable_test_vendor_code = SEA
cable_test_order_part_number = A_6152B1016
cable_test_meritor_Drawing_Revision = A
